### ISSUE TITLE
Local setup

### ISSUE THREAD

**Issue by PhilGarb** [chrisjpatty/flume#35]
I would like to try out different theming approaches to help out with #18. I see that there is an example directory to test the library during development. I do however have difficulties running it. I see, that flume (node-editor), react and react-dom are linked locally. Is that necessary to run the example? I have tried installing react and react-dom and npm linking the node-editor to the example, but I get the error: `Cannot read property 'thisCompilation' of undefined` when running `npm run start`.

@chrisjpatty could you elaborate on how to setup the library for local development?

**Comment by chrisjpatty** [comment]
@PhilGarb Sorry for the hassle getting your local env setup. I'll put together a contributors guide so this is a little more seamless in the future. For now though, the main thing is you'll need to use `yarn` instead of npm. The way the example is linked to the main library relies on some yarn-specific syntax. The easiest way to get started is to open two terminals, one to the root, and one to the `/example` directory. In the root run `yarn start`, and then in the example run `yarn start`. That should get you started, but let me know if you run into any snags with it. I'm definitely interested in your theming experiments, so let me know how it goes!

**Comment by PhilGarb** [comment]
Thank you so much! It worked right away. I have never seen this syntax. Is this like npm or yarn link just in the package.json?

**Comment by chrisjpatty** [comment]
Yeah exactly, it tells it to treat the directory you specify as if it were a node module under the provided name. Pretty handy! It does have a couple pitfalls, and one of those is that the syntax for it is different between npm and yarn for some reason.
