### ISSUE TITLE
Any detailed steps on how to run this?

### ISSUE THREAD

**Issue by netgfx** [chrisjpatty/flume#42]
Is there some guide on how to run this? I've tried the steps provided on the ReadMe but I'm guessing it requires the setup of various other modules correct?

I didn't have much luck with the example as well.

**Comment by chrisjpatty** [comment]
Hey @netgfx, thanks for trying out Flume! The quick start guide can help you get started with a basic setup, it's available here: 
[Flume Quick Start](https://flume.dev/docs/quick-start)

I'm in the process of working on a contributors guide which will have instructions for using the example directory. Is there a specific problem you're having trying to get started?

**Comment by netgfx** [comment]
Thanks for the quick response. From the link that you shared along with other documentation I take it that flume requires a basic npm setup and the reactjs to be installed. Is anything else required?
I know it may sound very beginner like, but I believe it would be helpful if the guide assumed that all I had was an empty folder, what steps would I need to take to have the most basic functionality of flume and view that locally in my browser.

**Comment by netgfx** [comment]
@chrisjpatty So what I did was to install the default react project via `npx create-react-app my-app` then do `npm install flume` then create the config.js file as described here: https://flume.dev/docs/basic-config
and change the default `App.js` like this:
```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import { NodeEditor } from 'flume'
import config from './config'

function App() {
  return (
   <div style={{width: 800, height: 600}}>
      <NodeEditor
        portTypes={config.portTypes}
        nodeTypes={config.nodeTypes}
      />
    </div>
  );
}

export default App;
```

and then run `npm start` which opened the a browser tab and threw the following error:
```
./src/App.js
Attempted import error: './config' does not contain a default export (imported as 'config').
```

**Comment by chrisjpatty** [comment]
Sorry for the late reply, yes, it requires installation in a React project. Flume is best used in projects with fairly diverse logic requirements so there's some inherent assumptions that developers who need it will previously understand the basics of React. `create-react-app` is a great place to get started as you have. It looks like the error you're running into above is because your `config.js` file is not available relative to your `App.js` file. In the folder structure of your React project, your config.js file should be like this:

```
/src
   ├─ App.js
   ├─ config.js
```
However, keep in mind that this is only required for this specific example. You can create and store your configuration anywhere you like in your project, and then import and pass it to the `NodeEditor` component.

**Comment by netgfx** [comment]
@chrisjpatty App.js is on the same `src` folder as `config.js`  this is why the error I'm getting seems to weird to me. Is the `npm start` the right command? Again this is the default react project that gets automatically created with `npx create-react-app my-app`.
What else is required to run the basic Flume example?

**Comment by chrisjpatty** [comment]
Can you put your code on a public repository and share the link here? I'm having trouble visualizing how you have your code setup.

**Comment by netgfx** [comment]
I found the issue, on the config.js it needs `export { config };` at the end

and on App.js `import { config } from "./config";` to read it.

I think it would be nice to be included in the documentation. But I get that is something very basic and trivial.
