### ISSUE TITLE
`Cannot read property "contains" of null` exception with basic configuration on CodeSandbox.io

### ISSUE THREAD

**Issue by leoncvlt** [chrisjpatty/flume#50]
Hello! First of all thank you for this nice tool! I wanted to try and give it a spin so I opened https://codesandbox.io/ (my weapon of choice to quickly fire up some experiments), created a React template, and started following the quick start guide.

However, I get this error every time I create or delete a node / comment:
![image](https://user-images.githubusercontent.com/4929974/96767204-1c140280-13d4-11eb-8473-bec96ef11992.png)

It doesn't seem to be critical as I can dismiss it and keep working. My initial thought is that while the error is not critical, it still trips `react-error-overlay` used in `create-react-app`, which powers the React template in codesandbox - it keeps doing that even if I download the project as a .zip file and do normal offline development.

Here's the super simple Codesandbox: https://codesandbox.io/s/experiment-flume-ykvts

Weird thing is that I did found some simple examples among the project issues using Codesandbox, but the issue does not seem to appear in them (like https://codesandbox.io/s/dynamically-add-flume-types-example-forked-ypg7t?file=/src/App.js), and I can't tell what's different.

Thanks!
L

**Comment by chrisjpatty** [comment]
Hey @leoncvlt ! I took a look at your sandbox, and at first I thought it might be because you don't have any props on your node editor, but adding them doesn't seem to fix it. Thanks for reporting this, there must be some edge case here I haven't covered sufficiently. I'm going to do some digging and see if I can see what's going on. Should hopefully be a simple fix on my end. In the meantime, it looks like using the keyboard shortcuts (up, down, and enter) in the context menu doesn't trigger the error.

**Comment by chrisjpatty** [comment]
@leoncvlt This should be fixed now. I just published 0.5.2 with a hotfix for this crash. I forked your sandbox and upgraded and it appears to be working now, but let me know if you see the same issue.
